task: ISLR
data:
  input_data: videos #features, gloss
  input_streams:
    - rgb
  use_keypoints:
    - pose
    - mouth_half
    - hand
    - face_others_1_3
#  zip_file: ../../data/csl-daily/sentence_frames-512x512.zip
  zip_file: /group/30106/neilzrzhang/2025H1/csl-daily/frames_512x512.zip
  train: ../../data/csl-daily/csl-daily.train
  dev: ../../data/csl-daily/csl-daily.dev
  test: ../../data/csl-daily/csl-daily.test
  dataset_name: csl_kp
  level: word #word or char
  txt_lowercase: true
  num_output_frames: -1
  max_sent_length: 400
  transform_cfg:
    img_size: 224
    color_jitter: true
    bottom_area: 0.7 #to-do
    center_crop_size: 270 #to-change for csl
    center_crop: true
    randomcrop_threshold: 1
    aspect_ratio_min: 0.75
    aspect_ratio_max: 1.3
    temporal_augmentation:  #deprecated for ISLR
      tmin: 0.5
      tmax: 1.5
    index_setting:
      - consecutive  #train_p
      - pad  #train_m
      - central  #test_p
      - pad  #test_m
    mixup: 0.75_0.8
    from64: true
testing:
  cfg:
    recognition:
      beam_size: 1
training:
#  load_ckpt: results/nla_slr_wlasl_2000/ckpts/best.ckpt
#  overwrite: true
  model_dir: results/cls-daily_keypoints
#  random_seed: 321
#  shuffle: True
  num_workers: 16
  batch_size: 1  #to-debug!
#  total_epoch: 100
#  keep_last_ckpts: 1
#  validation:
#    unit: epoch
#    freq: 1
#    cfg:
#      recognition:
#        beam_size: 1
#  optimization:
#    optimizer: Adam
#    learning_rate:
#      default: 1.0e-3
#    weight_decay: 0.001
#    betas:
#    - 0.9
#    - 0.998
#    scheduler: cosineannealing
#    t_max: 100
model:
  RecognitionNetwork:
    GlossTokenizer:
      gloss2id_file: ../../data/csl-daily/gloss2ids.pkl
    s3d:
      pretrained_ckpt: ../../pretrained_models/s3ds_actioncls_ckpt #from K400
      use_block: 5
      freeze_block: 0
    keypoint_s3d:
      in_channel: 0 # placeholder
      pretrained_ckpt: ../../pretrained_models/s3ds_actioncls_ckpt #from K400
      use_block: 5
      freeze_block: 0
    heatmap_cfg:
      raw_size:
        - 512
        - 512 #associated with name2keypoint file
      input_size: 112
      sigma: 8
    fuse_method: four_type3
    lateral:
      pose2rgb: true
      rgb2pose: true
      variant_pose2rgb: null
      variant_rgb2pose: null
      interpolate: false
      kernel_size:
        - 1
        - 3
        - 3
      fusion_features:
        - c1
        - c2
        - c3
        - c4
    pyramid:
      version: v1
      rgb: null
      pose: null
    aux_head:
      head_weight_rgb: 0.2
      head_weight_keypoint: 0.5
      num: 0
    visual_head:
      variant: sep_conv
      use_extra_linear: false  #for joint head only
      input_size: 1024
      hidden_size: 512  #deprecated
      ff_size: 2048  #deprecated
      pe: True  #deprecated
      ff_kernelsize:  #deprecated
        - 3
        - 3
      word_emb_dim: 300
      temp: 0.1
      contras_setting: dual_ema_cosine
      topk: 1000
    label_smooth: word_emb_sim_softmax_0.2_0.5
    contras_loss_weight: 1.0
    language_apply_to: rgb_keypoint_joint  #apply to which head?
